### ISSUE TITLE
DLL fail to load

### ISSUE THREAD

**Issue by Cr1ing3** [bananasmoothii/QuizletBypass#1]
File "C:\Users\-----\Quizlet\QuizletBypass-master\venv\lib\site-packages\Levenshtein\__init__.py", line 31, in <module>
    from Levenshtein.levenshtein_cpp import (
ImportError: DLL load failed while importing levenshtein_cpp: The specified module could not be found.

Not super great with programming so I don't know where to start with debugging. I installed the dependencies, so I don't know what it's error is. Could it just be something with my machine?

**Comment by bananasmoothii** [comment]
That's odd, seems like your Levenshtein package is broken. What Windows version are you using ?
I am on windows 11 and it works fine for me, maybe try to reinstall it with
```bash
pip uninstall levenshtein python-Levenshtein
pip install levenshtein
```

It could also be your antivirus deleting the files thinking it is a virus, make sure to prevent that.

If none of this works, you can also remove levenshtein from the script as it is not very useful (you can just check for total equality or no equality at all instead of calculating the distance)

**Edit:** I've just noticed you're using venv, try not to use that and use python's default `pip` instead

**Comment by Cr1ing3** [comment]
Ah, the antivirus might be the problem. BitDefender thinks everything is trying to destroy my computer. Yes - I am using Windows 11 too. I was using the console in PyCharm which was also probably contributing to the problem. I'll give your suggestions a try right now!

**Comment by Cr1ing3** [comment]
Ok so -
I tried uninstalling and reinstalling python and I added python to PATH this time. That fixed some of the problems using pip that I was having. I tried using levenshtein and it installed correctly, but I still had a missing DLL error (nothing from my antivirus and no venv this time). I removed levenshtein from the script and it works perfectly now! Thanks for the help. Cheers!

**Comment by bananasmoothii** [comment]
Windows just being Windows, I guess... Anyway, glad I could help !
