### ISSUE TITLE
May I ask what is the right link of my quizlet?

### ISSUE THREAD

**Issue by STEVENTAN100** [bananasmoothii/QuizletBypass#2]
Paste the link of your quizlet: https://quizlet.com/explanations/textbook-solutions/operating-system-concepts-10th-edition-9781119329480/chapter-1-exercises-20-b57c4750-6263-4c71-8919-9ef883cba450

No cards found, please check if the link is correct

I receive the above message, and I don't know what's the right link? Please show me an example, thanks so much!

**Comment by bananasmoothii** [comment]
Hello,
QuizletBypass is only for practicing the writing exercise of Quizlet, which is locked behind a paywall. A valid link is a link with flashcards, since that's the only thing with questions and answer, for example: https://quizlet.com/jp/874491163/elementlesson-8-playing-the-enemy-flash-cards/?funnelUUID=d44c373a-3cb9-4ccb-96e2-5ed95bf5ba55
If you find a flashcard list related to your lesson, it should work

**Comment by STEVENTAN100** [comment]
Oh, I see, maybe it doesn't work for textbook solutions, thanks anyway!

**Comment by bananasmoothii** [comment]
You're welcome!
